# Generated by Django 4.2.9 on 2024-03-11 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutrePersonneScientifique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_fiche', models.IntegerField()),
                ('nom_complet', models.CharField(max_length=255)),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, null=True)),
                ('numero_telephone', models.CharField(max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='profil_photos/')),
                ('date', models.DateTimeField(auto_now=True)),
                ('titre_academique', models.CharField(max_length=255, null=True)),
                ('nom_etablissement', models.CharField(max_length=255, null=True)),
                ('adresse_etablissement', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategorieScientifique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie_scientifique', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Faculte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_faculte', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_filiere', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_promotion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EtudiantInterne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_fiche', models.IntegerField()),
                ('nom_complet', models.CharField(max_length=255)),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('numero_telephone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='profil_photos/')),
                ('date', models.DateTimeField(auto_now=True)),
                ('faculte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculte', to='account.faculte')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filiere', to='account.filiere')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion', to='account.promotion')),
            ],
        ),
        migrations.CreateModel(
            name='Bibliothecaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=255)),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('numero_telephone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='profil_photos/')),
                ('date', models.DateTimeField(auto_now=True)),
                ('specialite', models.CharField(max_length=255)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Annee_academique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_academique', models.CharField(max_length=20)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annees_academiques', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
