# Generated by Django 4.2.9 on 2024-03-21 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiantinterne',
            name='faculte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiants', to='account.faculte'),
        ),
        migrations.AlterField(
            model_name='etudiantinterne',
            name='filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiants', to='account.filiere'),
        ),
        migrations.AlterField(
            model_name='etudiantinterne',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiants', to='account.promotion'),
        ),
    ]
