# Generated by Django 4.2.9 on 2024-03-23 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_etudiantinterne_faculte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filiere',
            name='faculte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.faculte'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='filiere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.filiere'),
        ),
    ]
