# Generated by Django 4.2.9 on 2024-03-23 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_filiere_faculte_promotion_filiere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='filiere',
        ),
        migrations.AddField(
            model_name='promotion',
            name='faculte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.faculte'),
        ),
    ]
