# Generated by Django 3.2 on 2024-07-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20240704_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibliothecaire',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='photos_profil/'),
        ),
    ]
