# Generated by Django 3.2 on 2024-06-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0006_auto_20240622_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='exemplaire',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='scan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
