# Generated by Django 3.2 on 2024-06-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0007_auto_20240622_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='exemplaire',
        ),
        migrations.RemoveField(
            model_name='book',
            name='scan',
        ),
        migrations.AddField(
            model_name='book',
            name='cote_book',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='nbr_exemplaire',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='num_invetaire',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
