# Generated by Django 3.2 on 2024-06-25 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0008_auto_20240624_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='return_at',
            new_name='expiration_date',
        ),
        migrations.CreateModel(
            name='CancelledReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField()),
                ('cancelled_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
