# Generated by Django 3.2 on 2024-06-25 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0009_auto_20240625_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
