# Generated by Django 3.2 on 2024-06-29 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0012_auto_20240629_2304'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('user', 'book')},
        ),
    ]
