# Generated by Django 3.2 on 2024-07-13 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0013_alter_reservation_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoteLivre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cote_livre', models.CharField(blank=True, max_length=250, null=True)),
                ('nb_selections', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='cote_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookstore.cotelivre'),
        ),
    ]
