# Generated by Django 4.2.9 on 2024-03-11 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoteLivre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cote_livre', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domaine_recherche', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Visiteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Etudiant', 'Etudiant'), ('Bibliothecaire', 'Bibliothecaire'), ('Autre', 'Autre')], max_length=255, null=True)),
                ('autre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.autrepersonnescientifique')),
                ('biblio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.bibliothecaire')),
                ('etudiant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.etudiantinterne')),
            ],
        ),
        migrations.CreateModel(
            name='BibliothequePhysique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('numero_inventaire_livre', models.CharField(max_length=50)),
                ('observation', models.BooleanField()),
                ('coteLivre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coteLivre', to='fiches.cotelivre')),
                ('visiteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiches.visiteur')),
            ],
        ),
        migrations.CreateModel(
            name='BibliothequeNumerique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline', to='fiches.discipline')),
                ('visiteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiches.visiteur')),
            ],
        ),
    ]
