# Generated by Django 4.2.9 on 2024-03-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotelivre',
            name='nb_selections',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='discipline',
            name='nb_selections',
            field=models.IntegerField(default=0),
        ),
    ]
