# Generated by Django 3.2 on 2024-07-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_consultation', models.CharField(choices=[('P', 'Physique'), ('N', 'Numérique')], max_length=1)),
                ('date', models.DateField()),
                ('cote_livre', models.CharField(blank=True, max_length=100, null=True)),
                ('no_inventaire_livre', models.CharField(blank=True, max_length=100, null=True)),
                ('heure_debut', models.TimeField(blank=True, null=True)),
                ('heure_fin', models.TimeField(blank=True, null=True)),
                ('nombre_heures', models.DurationField(blank=True, null=True)),
                ('observations', models.CharField(blank=True, max_length=255, null=True)),
                ('domaine_recherche', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fiche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=1)),
                ('telephone', models.CharField(max_length=15)),
                ('annee_academique', models.CharField(max_length=9)),
                ('promotion_filiere', models.CharField(max_length=255)),
                ('consultations', models.ManyToManyField(to='ficheapp.Consultation')),
            ],
        ),
    ]
