# Generated by Django 3.2 on 2024-07-05 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ficheapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiche',
            name='consultations',
        ),
        migrations.AddField(
            model_name='consultation',
            name='fiche',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='ficheapp.fiche'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='observations',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='type_consultation',
            field=models.CharField(blank=True, choices=[('P', 'Physique'), ('N', 'Numérique')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='annee_academique',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='genre',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='nom_complet',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='promotion_filiere',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='telephone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
