# Generated by Django 3.2 on 2024-07-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficheapp', '0002_auto_20240705_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiche',
            name='numero_fiche',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fiche',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='photos_profil/'),
        ),
        migrations.AlterUniqueTogether(
            name='fiche',
            unique_together={('numero_fiche', 'annee_academique', 'nom_complet')},
        ),
    ]
