# Generated by Django 3.2 on 2024-07-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficheapp', '0003_auto_20240705_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiche',
            name='annee_academique',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
