# Generated by Django 3.2 on 2024-07-09 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficheapp', '0004_alter_fiche_annee_academique'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiche',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
