# Generated by Django 3.2 on 2024-07-13 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ficheapp', '0005_fiche_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoteLivre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cote_livre', models.CharField(max_length=250)),
                ('nb_selections', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domaine_recherche', models.CharField(max_length=250)),
                ('nb_selections', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='consultation',
            name='cote_livre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='ficheapp.cotelivre'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='domaine_recherche',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='ficheapp.discipline'),
        ),
    ]
