# Generated by Django 5.1.5 on 2025-01-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficheapp', '0006_auto_20240713_1137'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fiche',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='fiche',
            constraint=models.UniqueConstraint(fields=('numero_fiche', 'annee_academique', 'nom_complet'), name='unique_fiche'),
        ),
    ]
